### PR TITLE
implement extraJarFiles() for java builds

### PR DESCRIPTION
**Pull request by cuchaz**
fixes issue #41, implements issue #43

I think I matched the style of the codebase. If you want any changes, let me know. =)

### CODE REVIEW

**Comment by cuchaz** [comment]
Ok, I've made the changes. Does this look good?

**Comment by djeang** [comment]
Almost perfect. You just have to rename `extraFiles( tree )` to `extraFilesInJar( tree )` or so.  I think this name is more catch even if more verbose. I am afraid that 'extraFiles' sounds to vague. Any other suggestion welcome.

**Comment by cuchaz** [comment]
ok, renamed. How's that?

**Comment by djeang** [comment]
Fine. Thanks you for your great help :-)
Your participation is really worthfull to make Jerkar better !

**Pull request merged**
