### PR TITLE
only add scope mappings to module dependencies

### LINKED ISSUE #50: JkImport doesn't allow file dependencies?
My build script,
```
@JkImport("path/to/jar.jar")
public class Build extends JkJavaBuild {
    ...
}
```
causes jerkar to throw an exception when it tries to compile the build classes:
```
java.lang.IllegalStateException: This dependency is type of org.jerkar.api.depmanagement.JkFileSystemDependency. Expecting JkModuleDependency.
	at org.jerkar.api.depmanagement.JkScopedDependency.withScopeMapping(JkScopedDependency.java:160)
	at org.jerkar.api.depmanagement.JkDependencies.withDefaultScopeMapping(JkDependencies.java:136)
	at org.jerkar.tool.Project.buildDefDependencies(Project.java:192)
	at org.jerkar.tool.Project.getBuildDefDependencyResolver(Project.java:279)
	at org.jerkar.tool.Project.compile(Project.java:84)
	at org.jerkar.tool.Project.compile(Project.java:72)
	at org.jerkar.tool.Project.execute(Project.java:121)
	at org.jerkar.tool.Main.main(Main.java:32)
```

The docs for `JkImport` annotation says it supports file dependencies, but the code seems to expect only module dependencies.

### PR DESCRIPTION
**Pull request by cuchaz**
This fixes #50 for me. I'm not sure if it's the correct fix overall though.

### CODE REVIEW

**Comment by cuchaz** [comment]
weird... travis is saying the unit tests failed:
```
     [java] |  |  Run JUnit tests ... 
     [java] 44 test(s) run, 1 failure(s), 1 ignored. In 1769 milliseconds.
```
The tests pass on my local machine though:
```
|  |  Run JUnit tests ... 
|  |  |  44 test(s) run, 0 failure(s), 1 ignored. In 1824 milliseconds.
```
There must be something different about the tests. Investigating...

**Comment by cuchaz** [comment]
Oh, haha, found the problem. A failing test was apparently added really recently. =P

https://github.com/jerkar/jerkar/blob/master/org.jerkar.core/src/test/java/org/jerkar/api/depmanagement/JkScopedDependencyTest.java#L65

**Comment by djeang** [comment]
I have added mistakenly an unrelevant test. I remove it now travis build pass.
Commiting your fix would requiere deeper on side effect. So I prefer to leave the code as is. Thanks anyway :-)

**Comment by djeang** [comment]
Sorry, I confused with another bug. your PR is ok.  Thanks !!!

**Pull request merged**
