### PR TITLE
implement plugin for protobuf

### PR DESCRIPTION
**Pull request by cuchaz**
I'm not sure if you want this as a built-in plugin, but I wrote a plugin for [protobuf](https://developers.google.com/protocol-buffers/) and thought I'd contribute it to the main project.

Here's a little snippet of how to use it:
```
public class Build extends JkJavaBuild {
	
	@JkProject("../otherProject")
	JkJavaBuild otherProject;
	
	public void doCompileProto() {
		
		String packageName = "package.name.for.protos";

		// clean folder before building (optional)
		JkUtilsProtobuf.deleteJavaFiles(sources(), packageName);

		// run protobuf compiler
		JkProtobufProcess.of()
			.andProtoFiles(JkFileTree.of(file("proto")))
			.andProtoDir(otherProject.baseDir().file("proto"))
			.withJavaDir(editedSources())
			.runSync();

		// suppress warnings in output java sources to avoid warning spam (optional)
		JkUtilsProtobuf.suppressWarnings(sources(), packageName);
	}
}
```

I tried to follow the style of the jerkar project as much as possible. Let me know if anything should be changed. Or if you're not interested in the plugin, that's fine too. =)

Also, I tried to modify the distrib-all build script a bit to make it easier to add plugins. Hopefully I didn't break anything.

### CODE REVIEW

**Comment by djeang** [comment]
Interisting.

However what you did is not properly said a "plugin" for Jerkar. It's more a utility class for performing protobuf compilation. A plugin is more an extension point for JkJavaBuild template [see section 7](http://project.jerkar.org/documentation/latest/reference.html).

The builtin plugin are here for historical reason : When I have developed up Jerkar, Jerkar was the first project it builds (jerkar builds itself). So has a proof of working, I made Jerkar project multi-module with plugin inside. 

Extension with other tools as you did fit better in separate project/repository. I can grant you in order you create new repositories in Jerkar organisation.

**Comment by cuchaz** [comment]
Well, I originally wanted the plugin to make a new task on the build class automatically. Something like "doCompileProto()" that could be configured with an options struct, but I couldn't find any examples in the codebase for how to do that. So for the first version, I just went with a library approach. In the future, I really do want to modify the behavior of the Build class system, so a plugin seems like the right way to do that, right?

As for whether or not it should be a built-in plugin, I have no idea. I couldn't find any information about how to write plugins, so I used an existing plugin as a template.

How do you think is a better way to write a plugin for this?

**Comment by djeang** [comment]
The best place to start writting a plugin write a plugin is looking at JkBuildPluginWar in jerkar core.
You'll see how you can implement extension point for JkJavaBuild. You may also find out that some hooks are missing in JkJavaBuild (I suppose that you want generate some code into genererated source). tell me we'll add it.

Note that you have to respect naming convention as `JkBuildPluginProtobuf` in order your class been auto-discovered by  Jerkar.

I have created repo [here](https://github.com/jerkar/protobuf-plugin) so you can put your code here soon or later.

Do not hesitate to ask for further explanation :-)

**Comment by cuchaz** [comment]
Thanks! It looks like `JkBuildPluginWar` extends `JkBuildPlugin`, but I don't see any hooks for adding new tasks. It seems jerkar discovers tasks by inspecting methods on the `JkBuild` subclass, but the only way to add methods to a class without editing its source (or using fancy bytecode hacks) is to use inheritance. Sadly, Java doesn't support multiple inheritance, so that doesn't seem like a good mechanism for adding tasks to build scripts in general. Is there some other way we can add tasks to build scripts without needing to add a method to the `JkBuild` subclass?

Also, thanks for the repo. I'll move my code there.

**Comment by djeang** [comment]
Well you have several options 

1. You can just create a lib so that it is reusable in any build class at the price of writing few line of code. For exemple, you can override the `JkJavaBuild#generateSources` method and implements some call to the lib inside.

2. You can create a reusable subclass of JkJavaBuild that override JkJavaBuild#generateSources`  as 1) and make your build class override this class. The limitation is mono inheritence

3. You can write a plugin for JkJavaBuild that hook the `JkJavaBuild#generateSources` to add behavior to it without subclassing.  As I was lazy I didn't implement yet such hook yet for this method as i did for `unitTestSources`.  It is not a big deal, you are welcome to implement it if you have time or I'll try to find some very soon.

I would take a combination of 1) and 3). I mean create a library that also contains a JkJavaBuildPlugin like this users has choice.

**Comment by djeang** [comment]
Having a look now... I am implementing something similar, just adding a generic hook prior compilation.

**Comment by cuchaz** [comment]
The trick is, I don't only want to compile protos when I build the whole project. When I'm developing code that uses the protos, I need to compile the protos (or re-compile them) and then write java code that uses them. This happens over and over again... write protos, compile, write java... re-write protos, compile, re-write java... and so on until I've gotten all the bugs out. =P

So I need to have a task that only runs the protobuf compiler, and I need to trigger it directly. Having the protobuf compiler triggered as part of some larger build-all-the-things task is useful when I'm doing a full build of the project, but it's not appropriate when I'm still developing the code that uses the protos.

I really would like just a single task that only runs the protobuf compiler and does nothing else.

**Comment by cuchaz** [comment]
Would be useful if I researched a way to allow plugins to add new tasks to builds without subclassing? I don't know much about how task discovery works yet, but I'd imagine there's code in jerkar somewhere that uses reflection to find a match to a task name from the command line. I could modify this code to also look in a special place where plugins have defined tasks.

**Comment by djeang** [comment]
Ok, so for me the most reasonnable/simple way of doing this is to start by creating a lib then in your build class, add the following lines 
```
    @JkDoc("Genererate source code from protobuf")
    public void protobuf() {
         JkProtobuf.of(this).generateFrom(new File('yourProtoFile'));
    }
    
    @Override
    public void compile() {
        protobuf();
        super.compile();
    }```

The of() factory constructs a JkProtobuf object configured for this build (by default, outputting code where mentioned by `generatedSources()`.  You can also m
add method like `outputDir(File dest)' for explicitly set the output and other params.

Like this you wont need the plugin mechanism. Just add your lib in the _build/libs/boot_ dir or use the @JkImport annotation. 

Is it ok ?

**Comment by cuchaz** [comment]
If we're not going to allow plugins to create build tasks, then sure, there's no need for my protobuf code to use the plugin system. It's better to just call the protobuf code as a library.

I'll update my code and move it to the new repo.

Thanks for your help. =)

**Comment by djeang** [comment]
Fine, then on top of it we may add a plugin class so we will see concretely if it has any added value. It's not a big deal.

**Comment by cuchaz** [comment]
I've finished my protobuf library and pushed it to the new repo you created for me:
https://github.com/jerkar/protobuf-plugin

This new design is a bit better than the old one I think, and much easier to use. =)

Do you have any suggestions or things I should change?

Also, what's the best way to publish the jar file, so the `JkImport` annotations work correctly for my library?

Thanks!

**Comment by djeang** [comment]
Great Job !!!  :-)

To push it to your personnal or shared binary repository (as nexus). To do that, just run `jerkar doPublish`. 

To render it public, as Jerkar is, you must deploy it on OSSRH.  This is not trivial since you don't have account. but I can push it for you.  I'am looking for a mean to share publish information at team level.

I will have a look soon and mabe make some suggestions.

Thanks !

**Comment by cuchaz** [comment]
I've made some improvements to the plugin and fixed any outstanding issues. Is there anything else that needs to be changed?

**Pull request closed without merging**
